### ISSUE TITLE
Web API Support discontinued ? 

### ISSUE THREAD

**Issue by diiiv9** [postlight/mercury-parser#255]
Has Mercury Reader discontinued support for the Web API ? If so , can you please tell me how can I run Mercury Reader on iOS ?

**Comment by adampash** [comment]
As you may have read in [our post](https://postlight.com/trackchanges/mercury-goes-open-source):

> Over time, we will deprecate the Mercury Parser API. We’ll do it slowly, with lots of warning and advance email notifications, and [drop-in replacement code](https://github.com/postlight/mercury-parser-api). We’ve committed to creating an easy path for people who want to use Mercury in any way they see fit, using open source, well-documented code that can be easily rolled into any other service or API. We want to put our energy there, making a more tractable web together—not behind a private, hosted API.

The big takeaway here, if you still need access to an API, is that we've also open-sourced the code that ran the Mercury Parser API, which you can find here:

https://github.com/postlight/mercury-parser-api

It runs on a serverless stack on AWS, where you get roughly 1 million requests/month for free. If that suits your needs, it should, hopefully, be a good fit. Otherwise you can use the Mercury Parser code in this repo to create your own tools to take the API's place however you see fit.
