### ISSUE TITLE
WordPress detection incorrect?

### ISSUE THREAD

**Issue by irfancharania** [postlight/mercury-parser#280]
Hi!

Thanks for open-sourcing this project. 

I was looking through the code and came across this line

https://github.com/postlight/mercury-parser/blob/15f7fa1e27fe6b47c87da40ba4fce9b2db7934ec/src/utils/dom/constants.js#L304

I think this XPath should be
meta[name=generator][**content**^=WordPress]

Check with examples: 
- https://observer.com
- https://uproxx.com/
- https://thoughtcatalog.com

The [fixtures](https://github.com/postlight/mercury-parser/tree/15f7fa1e27fe6b47c87da40ba4fce9b2db7934ec/fixtures) for these sites should be updated

**Comment by benubois** [comment]
Hi @irfancharania,

I believe the code and tests are correct. The reason why this works is because mercury is [normalizing all meta tags](https://github.com/postlight/mercury-parser/blob/b044cfa958014beae03c6f69a3b32499abe765af/src/resource/utils/dom/normalize-meta-tags.js#L21). This way they can be queried with the same selector.

**Comment by irfancharania** [comment]
That makes sense then! Thanks for clarifying
