### ISSUE TITLE
[REQUEST] Parsing pre-fetched html WITHOUT url

### ISSUE THREAD

**Issue by fungilation** [postlight/mercury-parser#324]
- **Platform**: Windows dev, Android emulator
- **Mercury Parser Version**: 2.0.0

Continuing from https://github.com/postlight/mercury-parser/issues/277

Supplying both url and html as params to `Mercury.parse()` works. BUT, it won't work without a url, or any url that won't resolve. See below test, which just truncates url to first 17 chars.

Is there a way to parse raw html to extract to "content", without any parsing or calling of url? This is to avoid double url calling and loading, when that url has obviously already been called elsewhere with resultant html `fetch`ed.

```js
Mercury.parse(url.substr(0, 17), {html: rawHtml}).then(result => console.log('Mercury parse:', result)).catch((error) => {
  console.log(index, 'Mercury error:', error)
})
```
Chrome devtools log something like this:
```js
"Mercury parse:" Error: CORS request rejected: https://www.cnbc.
    at on_response (blob:http://localhos…3a5eac74cd03:144137)
    at XMLHttpRequest.on_state_change (blob:http://localhos…3a5eac74cd03:144120)
    at XMLHttpRequest.dispatchEvent (blob:http://localhos…-3a5eac74cd03:29193)
    at XMLHttpRequest.setReadyState (blob:http://localhos…-3a5eac74cd03:28931)
    at XMLHttpRequest.__didCompleteResponse (blob:http://localhos…-3a5eac74cd03:28773)
    at blob:http://localhos…-3a5eac74cd03:28883
    at RCTDeviceEventEmitter.emit (blob:http://localhos…6-3a5eac74cd03:8785)
    at MessageQueue.__callFunction (blob:http://localhos…6-3a5eac74cd03:8207)
    at blob:http://localhos…6-3a5eac74cd03:7980
    at MessageQueue.__guard (blob:http://localhos…6-3a5eac74cd03:8161)
```

**Comment by toufic-m** [comment]
Hey @fungilation , the URL is required in order to select and use an adequate extractor/parser for content (based on the host/domain name), even if you are manually supplying the HTML.

If a site has a custom extractor, then that custom extractor would be used in order to optimally parse its content; sites that don't have custom extractors would fallback to using the generic extractor.

Additionally, supplying both the URL and HTML doesn't actually make a request to fetch content on that URL: https://github.com/postlight/mercury-parser/blob/master/src/resource/index.js#L18 , but rather returns a prepared response with the provided HTML.

**Comment by fungilation** [comment]
Ah, I see. Mocked valid response to not actually fetch with url, if html was supplied. That's all I wanted, to not double fetch.

Sidenote: the optional {html: rawHtml} should be documented on README.
