### ISSUE TITLE
"Unexpected token =>"

### ISSUE THREAD

**Issue by MastaBaba** [postlight/mercury-parser#391]
After getting the parser working on my own server as per [this](https://babakfakhamzadeh.com/replacing-postlights-mercury-scraping-service-with-your-self-hosted-copy/) list, the parser now fails. I have no idea where to start to resolve this problem.

I try to run the script below:

```
const Mercury = require('@postlight/mercury-parser');
const url = 'https://en.wikipedia.org/wiki/John_von_Neumann';
Mercury.parse(url).then(result => { console.log(result); } );
```

This results in this problem:

```
/home/{{my user}}/{{my server}}/public/x.js:3
Mercury.parse(url).then(result => { console.log(result); } );
                               ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

- **Platform**:

PHP7.2. What else do I need to put here?

- **Mercury Parser Version**:

How do I check this?

- **Node Version (if a Node bug)**:

0.12.0

- **Browser Version (if a browser bug)**:

Any.

## Expected Behavior

As before, I expect the script to return information about the page I pass on.

## Current Behavior

Script fails.

## Steps to Reproduce

No idea. The above script does this for me. Does it for others?

**Comment by toufic-m** [comment]
This is a Node.js error regarding lack of support for ES6's arrow functions in your current version of Node.js (0.12.0), which is very outdated and incompatible with Mercury Parser.

Your [instructions](https://babakfakhamzadeh.com/replacing-postlights-mercury-scraping-service-with-your-self-hosted-copy/) mention installing the minimum required version of Node.js, but it doesn't seem to be persisted since your platform details mention `0.12.0` as the Node.js version. If you have several version of Node.js installed via NVM, you might need to set version `8.10` as the default one.

[This article](https://davidwalsh.name/nvm) (also referenced in your instructions) describes how to check what versions of Node.js are installed and how to set a specific version as the default one.

**Comment by MastaBaba** [comment]
Thanks. I should have spotted that old version, indeed.

In fact, installing nvm does not (now?) appear to persist between SSH sessions for me.
