### ISSUE TITLE
I have multiple kindles. How do you configure which should be "send to kindle" recipient?

### ISSUE THREAD

**Issue by LongHawl** [postlight/mercury-parser#640]
- **Platform**:
- **Mercury Parser Version**:
- **Node Version (if a Node bug)**:
- **Browser Version (if a browser bug)**:

## Steps to Reproduce

1. 2. 3. 4.

**Comment by johnholdun** [comment]
Hi! I believe you can set up unique email address for device from the [Manage Your Kindle](https://www.amazon.com/hz/mycd/digital-console/alldevices) settings on the Amazon website. From there, you can choose the appropriate email to set in your Mercury Reader settings so that articles are sent to the device you expect. Hope this helps!
